# Generated by Django 3.0.3 on 2020-02-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creation_date',
            new_name='creation_timestamp',
        ),
        migrations.AddField(
            model_name='post',
            name='news_article_url',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
    ]
