# Generated by Django 3.0.3 on 2020-02-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_update_post_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('article_url', models.URLField(unique=True)),
                ('article_image_url', models.URLField()),
                ('publish_date', models.DateTimeField()),
            ],
        ),
    ]
